### PR TITLE
Change validation for dayOfTheWeek to accept 0

### PR DESCRIPTION
**Pull request by krishna-koushik**
In cron 0 = 7 = Sunday

### CODE REVIEW

**Comment by waneka** [comment]
@krishna-koushik thanks for the PR, this looks good. merging...

**Comment by krishna-koushik** [comment]
Thank you for merging this PR :) . could you perhaps increment the version so that i can use the original code instead of the forked repo code?

**Comment by rajeshwar-fissionlabs** [comment]
This is not correct. The standard values can be between 0 and 6 only.
https://crontab.guru/#2_5_3_4_6

**Comment by waneka** [comment]
see conversation in #17

**Comment by llamamoray** [comment]
Hi @waneka , any reason this wasn't released?

**Pull request merged**
